version: '{build}'
skip_non_tags: true 
image: Visual Studio 2017
environment:
  my_secret:
    secure: oB6h1YHPdFxVwg7++llRwg== # Encriptada em https://ci.appveyor.com/tools/encrypt
  my_salt:
    secure: ip3vQg3F/xDJ2tAs4dINX0ojuK7Z2Qujf3vIUV3fS0CsEpsHtoyrH8gY1KIic8tPCCOHBwaCAFDfRSyvnDvoKA==
branches:
  only:
  - master
configuration: Release
install:
  - cmd: echo %APPVEYOR_REPO_TAG_NAME%
  - cmd: dotnet restore
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: $(APPVEYOR_REPO_TAG_NAME)
  package_version: $(APPVEYOR_REPO_TAG_NAME)
  assembly_version: $(APPVEYOR_REPO_TAG_NAME)
  file_version: $(APPVEYOR_REPO_TAG_NAME)
  informational_version: $(APPVEYOR_REPO_TAG_NAME)
build:
  verbosity: minimal
  project: discord-webhook-client.sln
build_script:
  - cmd: dotnet build
  - ps: iex ((New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/appveyor/secure-file/master/install.ps1'))
  - cmd: appveyor-tools\secure-file -decrypt discord-webhook-client-test\bin\Release\netcoreapp2.1\testSettings.json.enc -secret %my_secret% -salt %my_salt%
  - cmd: dotnet pack
  - cmd: cd discord-webhook-client-test
  - cmd: dotnet test
artifacts:
  - path: '**\discord-webhook-client*.nupkg'
    name: discord-webhook-client-nuget
deploy:
  # NuGet
  - provider: NuGet
    api_key:
      secure: a4SVkFwIJ1khWZoaTG2f+dThjwSPSW+GU+LLaBFuR51hfqrpSMq/MszMjaMC0eVu # Encriptada em https://ci.appveyor.com/tools/encrypt
    skip_symbols: false
    artifact: discord-webhook-client-nuget
on_success:
  - echo Processo finalizado com sucesso!
